config/routes.rb
MusicApp::Application.routes.draw do

  root :to => 'navigations#index'

  resources :users do
    collection do
      get :activate
    end
  end

  resource :session

  resources :bands do
    resources :albums, only: ["index", "create", "new"]
  end

  resources :albums, except: ["index", "create", "new"] do
    resources :tracks, only: ["index", "create", "new"]
  end

  resources :tracks, except: ["index", "create", "new"]

  resources :notes, only: ["create", "destroy"]

end

app/models/track.rb
class Track < ActiveRecord::Base
  attr_accessible :track_title, :track_type, :lyrics, :album_id

  validates :track_title, presence: true, uniqueness: true
  validates :track_type, presence: true, inclusion: { in: %w(bonus regular), message:"%{value} is not a valid track type" }
  validates :lyrics, presence: true
  validates :album_id, presence: true

  belongs_to(
  :album,
  class_name: "Album",
  foreign_key: :album_id,
  primary_key: :id
  )

  has_many(
  :notes,
  class_name: "Note",
  foreign_key: :track_id,
  primary_key: :id
  )


end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController

  def new
    @album = Album.find(params[:album_id])
    @track = Track.new
    render :new
  end

  def create
    new_track = Track.new(params[:track])
    if new_track.save
      redirect_to track_url
    else
      render json: new_track.errors.full_messages
    end
  end

  def update
    updated_track = Track.find_by_id(params[:id])
    if updated_track.update_attributes(params[:track])
      redirect_to updated_track
    else
      render json: updated_track.errors.full_messages
    end
  end

  def edit
    @track = Track.find(params[:id])
    render :edit
  end

  def show
    @track = Track.find(params[:id])
    render :show
  end

  def destroy
    @current_album = Track.find(params[:id]).album
    Track.destroy(params[:id])
    redirect_to @current_album
  end

end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/tracks/_track_attr.html.erb
<h1><%= params[:action] == "new" ? "Add a Track" : "Edit Track" %></h1>

<form action="<%= params[:action] == "new" ? album_tracks_url : track_url %>" method="post">

  <% if params[:action] != "new" %>
    <input type="hidden"
           name="_method"
          value="PUT">
  <% end %>

  <input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">

  <br>

    <label>Track Title
      <input type="text" name="track[track_title]"
            value="<%= params[:action] == "new" ? "" : Track.find(params[:id]).track_title %>">
    </label>

  <br>

    <label>Album
      <select name="track[album_id]" >

        <% Album.all.each do |album| %>
          <option value="<%= album.id %>"
           <%= "selected = 'selected'" if album == @album %>"
           ><%= album.album_title %></option>
        <% end %>

      </select>
    </label>

  <br>

    <label>Lyrics
      <textarea name="track[lyrics]"><%= params[:action] == "new" ? "" : Track.find(params[:id]).lyrics %></textarea>
    </label>

  <br>

    <label>Type

      <input type="radio" name="track[track_type]" id="regular" value="regular"
      <%= "checked" if @track.track_type=="regular" %>>
      <label for"regular">Regular</label>

      <input type="radio" name="track[track_type]" id="bonus" value="bonus"
      <%= "checked" if @track.track_type=="bonus" %>>
      <label for"bonus">Bonus</label>

    </label>

  <br>

  <input type="submit" value="<%= params[:action] == "new" ? "Add Track" : "Edit Track" %>">

</form>

app/views/tracks/edit.html.erb
<%= render "track_attr" %>

app/views/tracks/new.html.erb
<%= render "track_attr" %>

app/views/tracks/show.html.erb
<h1><%= @track.track_title %></h1>

<br>

  <label>Band:
    <%= link_to @track.album.band.band_name, @track.album.band %>
  </label>

<br>

  <label>Album:
    <%= link_to @track.album.album_title, @track.album %>
  </label>

<br>

  <label>Lyrics:
    <%= @track.lyrics %>
  </label>

<br>

  <label>Type:
    <%= @track.track_type %>
  </label>

<br>
  <%= button_to "Edit Track", edit_track_url, method: :get %>
  <%= button_to "Delete Track", track_url, method: :delete %>

<h3>New Note</h3>
<form action="<%= notes_url %>" method="post">

  <input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">

  <label>Title
    <input type="text" name="note[title]">
  </label>

  <label>Body
    <input type="text" name="note[body]">
  </label>

  <input type="hidden" name="note[user_id]" value="<%= current_user.id %>">
  <input type="hidden" name="note[track_id]" value="<%= params[:id] %>">

  <input type="submit" value="Create New Post">

</form>


<h3>Existing Notes</h3>
  <ol>
    <% @track.notes.each do |note| %>
    <li> <%= note.user.email %> => <%= note.title %>: <%= note.body %><%= button_to "Delete Post", note_url(note.id), method: :delete %></li>
    <br>
    <% end %>
  </ol>