config/routes.rb
MusicApp::Application.routes.draw do

  root :to => 'navigations#index'

  resources :users do
    collection do
      get :activate
    end
  end

  resource :session

  resources :bands do
    resources :albums, only: ["index", "create", "new"]
  end

  resources :albums, except: ["index", "create", "new"] do
    resources :tracks, only: ["index", "create", "new"]
  end

  resources :tracks, except: ["index", "create", "new"]

  resources :notes, only: ["create", "destroy"]

end

app/models/album.rb
class Album < ActiveRecord::Base
  attr_accessible :album_title, :album_type, :band_id

  validates :album_title, presence: true, uniqueness: true
  validates :album_type, presence: true, inclusion: { in: %w(live studio), message:"%{value} is not a valid album type" }
  validates :band_id, presence: true

  belongs_to(
  :band,
  class_name: "Band",
  foreign_key: :band_id,
  primary_key: :id
  )

  has_many(
  :tracks,
  dependent: :destroy,
  class_name: "Track",
  foreign_key: :album_id,
  primary_key: :id
  )

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  def new
    @band = Band.find(params[:band_id])
    @album = Album.new
    render :new
  end

  def create
    new_album = Album.new(params[:album])
    if new_album.save
      redirect_to new_album
    else
      render json: new_album.errors.full_messages
    end
  end

  def update
    current_album = Album.find(params[:id])
    if current_album.update_attributes(params[:band])
      redirect_to current_album
    else
      render json: current_album.errors.full_messages
    end
  end

  def edit
    @album = Album.find(params[:id])
    @band = @album.band
    render :edit
  end
  #
  def show
    @album = Album.find(params[:id])
    render :show
  end

  def destroy
    @current_band = Album.find(params[:id]).band
    Album.destroy(params[:id])
    redirect_to @current_band
  end

end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/_album_attr.html.erb
<h1><%= params[:action] == "new" ? "Create Album" : "Edit Album" %></h1>

<form action="<%= params[:action] == "new" ? band_albums_url : album_url %>"
      method="post">

  <% if params[:action] != "new" %>
    <input type="hidden"
           name="_method"
          value="PUT">
  <% end %>

  <input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">
  <h2><%= @band.band_name %></h2>


  <br>

    <label>Album Title
      <input type="text" name="album[album_title]"
      value="<%= params[:action] == "new" ? "" : Album.find(params[:id]).album_title %>">
    </label>

  <br>

    <label>Band
      <select name="album[band_id]" >

        <% Band.all.each do |band| %>
          <option value="<%= band.id %>"
           <%= "selected = 'selected'" if band == @band %>"
           ><%= band.band_name %></option>
        <% end %>

      </select>
    </label>

  <br>

    <label>Type

      <input type="radio" name="album[album_type]" id="live" value="live"
      <%= "checked" if @album.album_type=="live" %>>
      <label for"live">Live</label>

      <input type="radio" name="album[album_type]" id="studio" value="studio"
      <%= "checked" if @album.album_type=="studio" %>>
      <label for"live">Studio</label>

    </label>

  <br>

  <input type="submit" value="<%= params[:action] == "new" ? "Create Album" : "Edit Album" %>">


</form>

app/views/albums/edit.html.erb
<%= render "album_attr" %>

app/views/albums/new.html.erb
<%= render "album_attr" %>

app/views/albums/show.html.erb
<h1><%= @album.album_title %></h1>

<br>

  <label>Band:
    <%= link_to @album.band.band_name, @album.band %>
  </label>

<br>

  <label>Tracks:
    <ul>
        <% @album.tracks.each do |track| %>
          <li><%= link_to track.track_title, track %></li>
        <% end %>
    </ul>
  </label>

<br>

  <label>Type:
    <%= @album.album_type %>
  </label>

<br>

  <%= button_to "Edit Album", edit_album_url, method: :get %>
  <%= button_to "Delete Album", album_url, method: :delete %>