config/routes.rb
MusicApp::Application.routes.draw do

  root :to => 'navigations#index'

  resources :users do
    collection do
      get :activate
    end
  end

  resource :session

  resources :bands do
    resources :albums, only: ["index", "create", "new"]
  end

  resources :albums, except: ["index", "create", "new"] do
    resources :tracks, only: ["index", "create", "new"]
  end

  resources :tracks, except: ["index", "create", "new"]

  resources :notes, only: ["create", "destroy"]

end

app/models/band.rb
class Band < ActiveRecord::Base
  attr_accessible :band_name

  validates :band_name, presence: true, uniqueness: true

  has_many(
  :albums,
  dependent: :destroy,
  class_name: "Album",
  foreign_key: :band_id,
  primary_key: :id
  )

end

app/controllers/bands_controller.rb
class BandsController < ApplicationController

  def index
    @all_bands = Band.all
    render :index
  end

  def new
    @band = Band.new
    render :new
  end

  def create
    new_band = Band.new(params[:band])
    if new_band.save
      redirect_to bands_url
    else
      render json: new_band.errors.full_messages
    end
  end

  def update
    updated_band = Band.find_by_id(params[:id])
    if updated_band.update_attributes(params[:band])
      redirect_to updated_band
    else
      render json: updated_band.errors.full_messages
    end
  end

  def edit
    @band = Band.find(params[:id])
    render :edit
  end

  def show
    @band = Band.find(params[:id])
    render :show
  end

  def destroy
    Band.destroy(params[:id])
    redirect_to bands_url
  end

end

app/helpers/bands_helper.rb
module BandsHelper
end

app/views/bands/_band_attr.html.erb
<h1><%= params[:action] == "new" ? "Add a Band" : "Edit Band" %></h1>

<form action="<%= params[:action] == "new" ? bands_url : band_url %>" method="post">

  <% if params[:action] != "new" %>
    <input type="hidden"
           name="_method"
          value="PUT">
  <% end %>

  <input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">

  <label>Band Name
    <input type="text" name="band[band_name]" value="<%= @band.band_name %>">
  </label>

  <input type="submit" value="<%= params[:action] == "new" ? "Add Band" : "Edit Band" %>">

</form>

app/views/bands/edit.html.erb
<%= render "band_attr" %>

app/views/bands/index.html.erb
<h1>All Bands!</h1>

<% @all_bands.each do |band| %>
  <%=link_to band.band_name, band%>
  <br>
<% end %>

app/views/bands/new.html.erb
<%= render "band_attr" %>

app/views/bands/show.html.erb
<h1><%= @band.band_name %></h1>
<ul>
    <% @band.albums.each do |album| %>
      <li><%= link_to album.album_title, album %></li>
      <ol>
        <% album.tracks.each do |track| %>
          <li><%= link_to track.track_title, track %></li>
        <% end %>
      </ol>
    <% end %>
</ul>

<br>

<%= button_to "Edit Band", edit_band_url, method: :get %>
<%= button_to "Delete Band", band_url, method: :delete %>